name: Build and Release EXE

on:
  push:
    tags:
      - "v*"  # Triggers when a new version tag is pushed (e.g., v1.0)

jobs:
  build:
    runs-on: windows-latest  # Runs the workflow on Windows OS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repository history is available

      - name: Set Up Python (if using Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies (Ensure PyInstaller is Installed)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        shell: cmd

      - name: Build Executable (Using PyInstaller)
        run: |
          pyinstaller --onefile YTClipper.py
        shell: cmd

      - name: Show Output Files (Debugging Step)
        run: |
          dir dist\
        shell: cmd

      - name: Archive Executable
        run: Compress-Archive -Path dist/YTClipper.exe -DestinationPath release.zip
        shell: pwsh

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
