name: Build and Release EXE

on:
  push:
    tags:
      - "v*"  # Triggers when a new version tag is pushed (e.g., v1.0)

jobs:
  build:
    runs-on: windows-latest  # Runs the workflow on Windows OS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repository history is available

      - name: Ensure GitHub has access to repo
        run: git fetch --unshallow

      - name: Set Up Python (if using Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies (if applicable)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Build Executable (Using PyInstaller for Python)
        run: |
          pyinstaller --onefile YTClipper.py  # Modify for your build process
        shell: cmd

      - name: Show Output Files (Debugging Step)
        run: |
          dir dist\
        shell: cmd

      - name: Archive Executable
        run: Compress-Archive -Path dist/
